import Foundation

/// A type that can be generated by language models.
///
/// Annotate your model types with the `@Generable` macro to allow the model to respond
/// to prompts by generating an instance of your type. Use the `@Guide` macro to provide
/// natural language descriptions of your properties, and programmatically control
/// the values that the model can generate.
///
/// ## Example
///
/// ```swift
/// @Generable
/// struct WeatherReport {
///   @Guide("The current temperature in Celsius")
///   let temperature: Int
///     
///   @Guide("Brief description of current conditions")
///   let conditions: String
///
///   @Guide("Chance of precipitation as percentage", .range(0...100))
///   let precipitationChance: Int
/// }
/// 
/// // Use with an LLM
/// let report = try await llm.reply(
///   to: [UserMessage(chunks: [.text("What's the weather in Paris?")])],
///   returning: WeatherReport.self
/// )
/// ```
public protocol Generable: Codable, Sendable {
  // TODO: Implementation will be added as the design evolves
}

// MARK: - Basic Type Conformances

/// String conforms to Generable for simple text generation use cases.
extension String: Generable {}